version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_stat_statements
      - -c
      - pg_stat_statements.track=all
      - -c
      - log_statement=all
      - -c
      - log_duration=on
      - -c
      - log_min_duration_statement=0
      - -c
      - "log_line_prefix=%t [%p] user=%u db=%d app=%a client=%h "
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manga_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d manga_tracker"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  mage:
    env_file:
      - .env
    build:
      context: .
      dockerfile: mage.Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manga_tracker
      DBT_PROJECT_NAME: manga_tracker_dbt
    ports:
      - "6789:6789"
    volumes:
      - .:/home/src/
    restart: on-failure:5
    depends_on:
      postgres:
        condition: service_healthy
  flyway:
    image: flyway/flyway:10
    container_name: flyway
    command: migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/manga_tracker
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
      FLYWAY_DEFAULT_SCHEMA: public
    volumes:
      - ./manga_tracker/utils/migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure:5
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: manga_api
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/manga_tracker
    ports:
      - "8000:8000"
    volumes:
      - ./manga_tracker/api:/app/manga_tracker/api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure:5
  metabase:
    image: metabase/metabase:v0.55.12
    container_name: metabase
    hostname: metabase
    env_file:
      - .env
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: postgres
      MB_DB_PORT: 5432
      MB_DB_NAME: metabase
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000
volumes:
  postgres_data: